# Generated by Django 3.2 on 2021-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tigID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('on_sale', models.BooleanField(default=False)),
                ('producer_price', models.FloatField(default=0)),
                ('retail_price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('qty_stock', models.IntegerField(default=0)),
                ('qty_sold', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ('tigID',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('tigID', models.IntegerField()),
                ('operation', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
