# Generated by Django 3.1.7 on 2021-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigAPI', '0002_auto_20210415_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
