# Generated by Django 3.2 on 2021-04-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigAPI', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
